resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/5.yaml

packages:
- mig
- mig-client
- mig-server
- mig-extra
- mig-swagger-ui
- mig-wai
- mig-rio
