name:                mig-server
version:             0.1.0.0
github:              "githubuser/mig-server"
license:             BSD3
author:              "Anton Kholomiov"
maintainer:          "example@example.com"
copyright:           "2023 Anton Kholomiov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
category:            Web
synopsis:            Build lightweight and composable servers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  With library mig we can build lightweight and composable servers.
  There are only couple of combinators to assemble servers from parts.
  It supports generic handler functions as servant does. But strives to use more
  simple model for API. It does not go to describing Server API at type level which
  leads to simpler error messages.
  .
  The main features are:
  .
  * lightweight library
  .
  * expressive DSL to compose servers
  .
  * type-safe handlers
  .
  * handlers are encoded with generic haskell functions
  .
  * built on top of WAI and warp server libraries.
  .
  Example of hello world server:
  .
  > import Mig.Json.IO
  >
  > -- | We can render the server and run it on port 8085.
  > -- It uses wai and warp.
  > main :: IO ()
  > main = runServer 8085 server
  >
  > -- | Init simple hello world server which
  > -- replies on a single route
  > server :: Server IO
  > server =
  >   "api" /. "v1" /.
  >     mconcat
  >       [ "hello" /. hello
  >       , "bye" /. bye
  >       ]
  >
  > -- | Handler takes no inputs and marked as Get HTTP-request that returns Text.
  > hello :: Get Text
  > hello = Get $ pure "Hello World"
  >
  > -- | Handle with URL-param query and json body input as Post HTTP-request that returns Text.
  > bye :: Query "name" Text -> Body ByeRequest -> Post Text
  > bye (Query name) (Body req) = Post $
  >   pure $ "Bye to " <> name <> " " <> req.greeting
  .
  Please see:
  .
  * quick start guide at <https://github.com/anton-k/mig#readme>
  .
  * examples directory for more fun servers: at <https://github.com/anton-k/mig/tree/main/examples/mig-example-apps#readme>

language: GHC2021

default-extensions:
  - DerivingStrategies
  - DuplicateRecordFields
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings
  - StrictData
  - TypeFamilies

dependencies:
- aeson
- base >= 4.7 && < 5
- mig
- mig-wai
- blaze-markup
- http-types
- text
- containers
- bytestring
- exceptions
- mtl
- http-api-data
- openapi3
- blaze-html

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
