name:                mig-server
version:             0.1.0.0
github:              "githubuser/mig-server"
license:             BSD3
author:              "Anton Kholomiov"
maintainer:          "example@example.com"
copyright:           "2023 Anton Kholomiov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mig-server#readme>

language: GHC2021

default-extensions:
  - OverloadedRecordDot
  - DuplicateRecordFields
  - OverloadedStrings
  - StrictData
  - TypeFamilies
  - LambdaCase

dependencies:
- aeson
- base >= 4.7 && < 5
- mig
- wai
- warp
- blaze-markup
- http-types
- text
- containers
- bytestring
- exceptions
- mtl
- http-api-data
- openapi3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
